language: java

jdk:
  - oraclejdk8

stages:
  - name: build
  - name: release
    if: branch = release

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: release
      script: ./gradlew run